// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCukHtc_BTSGTlN9uklwBn_AbWGmIUGo1Q',
    appId: '1:305225712559:web:ca620a1b59a2f5f52d255a',
    messagingSenderId: '305225712559',
    projectId: 'storeandservice',
    authDomain: 'storeandservice.firebaseapp.com',
    storageBucket: 'storeandservice.appspot.com',
    measurementId: 'G-995GW2WCBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC14EaxDg6CT45LlPRwowwK9eBlygnnqvI',
    appId: '1:305225712559:android:ba70ec66948bbd172d255a',
    messagingSenderId: '305225712559',
    projectId: 'storeandservice',
    storageBucket: 'storeandservice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYn7OwUWIO3OqW85wMmpD35idU1OhB8Yk',
    appId: '1:305225712559:ios:0f1f50ead6d810592d255a',
    messagingSenderId: '305225712559',
    projectId: 'storeandservice',
    storageBucket: 'storeandservice.appspot.com',
    iosBundleId: 'com.example.serviceandstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYn7OwUWIO3OqW85wMmpD35idU1OhB8Yk',
    appId: '1:305225712559:ios:0f1f50ead6d810592d255a',
    messagingSenderId: '305225712559',
    projectId: 'storeandservice',
    storageBucket: 'storeandservice.appspot.com',
    iosBundleId: 'com.example.serviceandstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCukHtc_BTSGTlN9uklwBn_AbWGmIUGo1Q',
    appId: '1:305225712559:web:4bbcabe1af1fe9fd2d255a',
    messagingSenderId: '305225712559',
    projectId: 'storeandservice',
    authDomain: 'storeandservice.firebaseapp.com',
    storageBucket: 'storeandservice.appspot.com',
    measurementId: 'G-E6QKJGHHYP',
  );
}
